### ISSUE TITLE
Prefab missing on the latest commit.

### ISSUE THREAD

**Issue by Yabusaki-KS47** [veryfancypants/hs2_blender_export#3]
Python: Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\hs2_blender_export\importer.py", line 765, in import_body
    load_textures(arm, body, hair_color, eye_color, suffix)
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\hs2_blender_export\importer.py", line 276, in load_textures
    with bpy.data.libraries.load(os.path.dirname(__file__)+"/assets/prefab_materials_meshexporter.blend") as (data_from, data_to):
OSError: load: C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\hs2_blender_export\assets\prefab_materials_meshexporter.blend failed to open blend file

we still need that prefab after all boss.

**Comment by Yabusaki-KS47** [comment]
Re-read and realized it was WIP and probably will be fixed in the future.
