### ISSUE TITLE
Import Issues

### ISSUE THREAD

**Issue by Jerimyhawk** [veryfancypants/hs2_blender_export#6]
Constantly running into the following error when importing my model.
I am a first time user of this plugin so bear with me!

Trying to texture 001 as clothing
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\hs2_blender_export-main\__init__.py", line 892, in execute
    arm=importer.import_body(self.filepath,
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\hs2_blender_export-main\importer.py", line 1019, in import_body
    load_textures(arm, body, hair_color, eye_color, suffix)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\hs2_blender_export-main\importer.py", line 451, in load_textures
    m = mesh.materials[0]
IndexError: bpy_prop_collection[index]: index 0 out of range, size 0

**Comment by veryfancypants** [comment]
One of the clothing items (or possibly hair items) has no material on it. This is unexpected and I've never seen this behavior. I'll work around it, but check that your export settings match what's shown in the screenshot in the readme.

**Comment by timm1k** [comment]
I had the same, for me it was missing "Create generic shader/materials" option on export

**Comment by NalihznehC** [comment]
Similar problem here, only the skin is textured, and the mesh size is approximately 0.9 times the armature scale.
`Python: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.5\scripts\addons\hs2_blender_export-main\importer.py", line 1020, in import_body
    load_textures(arm, body, hair_color, eye_color, suffix)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.5\scripts\addons\hs2_blender_export-main\importer.py", line 435, in load_textures
    m = mesh.materials[0]
        ~~~~~~~~~~~~~~^^^
IndexError: bpy_prop_collection[index]: index 0 out of range, size 0`
